stages:
  - compile
  - build
  - test
  - deploy
  - post-deploy

kics-iac-sast:
  stage: post-deploy
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: on_success
  needs:
    - terraform_deploy

terraform_validate:
  stage: build
  extends: .terraform:validate
  script:
    - gitlab-terraform validate

terraform_build:
  stage: test
  extends: .terraform:build
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  needs:
    - terraform_validate

terraform_deploy:
  stage: deploy
  extends: .terraform:deploy
  allow_failure: false
  script:
    - gitlab-terraform apply
  needs:
    - terraform_build
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: manual

terraform_destroy:
  stage: deploy
  extends: .terraform:destroy
  allow_failure: false
  script:
    - gitlab-terraform destroy
  needs:
    - terraform_build
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: manual

include:
  - template: Terraform/Base.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.latest.gitlab-ci.yml
  - template: Security/SAST-IaC.latest.gitlab-ci.yml
